@extends('Dashboard.layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="container-xxl flex-grow-1 container-p-y">
            <div class="row gy-6">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="mb-0">Hikers Management</h5>
                        <div class="card-header-elements">
                            <input type="text" id="searchInput" class="form-control" placeholder="Search hikers..."
                                style="width: 250px;">
                        </div>
                    </div>
                    <div class="table-responsive text-nowrap">
                        <table class="table" id="hikersTable">
                            <thead>
                                <tr>
                                    <th>Hiker Name</th>
                                    <th>Email</th>
                                    <th>Mountain</th>
                                    <th>Check-in Time</th>
                                    <th>Check-out Time</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody class="table-border-bottom-0">
                                <!-- Data will be loaded via AJAX -->
                            </tbody>
                        </table>
                    </div>

                    <!-- Loading spinner -->
                    <div id="loadingSpinner" class="text-center p-4" style="display: none;">
                        <div class="spinner-border text-primary" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                    </div>

                    <!-- No data message -->
                    <div id="noDataMessage" class="text-center p-4" style="display: none;">
                        <p class="text-muted">No hikers found.</p>
                    </div>

                    <!-- Pagination -->
                    <div class="card-footer">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <span id="tableInfo" class="text-muted">Showing 0 to 0 of 0 entries</span>
                            </div>
                            <div class="col-md-6">
                                <nav aria-label="Table pagination">
                                    <ul class="pagination justify-content-end mb-0" id="pagination">
                                        <!-- Pagination will be generated by JavaScript -->
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="content-footer footer bg-footer-theme">
            <div class="container-xxl">
                <div
                    class="footer-container d-flex align-items-center justify-content-between py-4 flex-md-row flex-column">
                    <div class="mb-2 mb-md-0">
                        &#169;
                        <script>
                            document.write(new Date().getFullYear());
                        </script>, Mountain Management System
                    </div>
                </div>
            </div>
        </footer>

        <div class="content-backdrop fade"></div>
    </div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function() {
            let currentPage = 1;
            let itemsPerPage = 10;
            let searchTerm = '';
            let totalRecords = 0;
            loadHikers();

            let searchTimeout;
            $('#searchInput').on('keyup', function() {
                clearTimeout(searchTimeout);
                searchTerm = $(this).val();
                searchTimeout = setTimeout(function() {
                    currentPage = 1;
                    loadHikers();
                }, 500);
            });

            function loadHikers() {
                showLoading();
                $.ajax({
                    url: '{{ route('hikers.getData') }}',
                    type: 'GET',
                    data: {
                        search: searchTerm,
                        start: (currentPage - 1) * itemsPerPage,
                        length: itemsPerPage,
                        order_column: 'mb.checkin_time',
                        order_dir: 'desc'
                    },
                    success: function(response) {
                        hideLoading();
                        totalRecords = response.recordsTotal;
                        if (response.data && response.data.length > 0) {
                            renderTable(response.data);
                            renderPagination();
                            updateTableInfo();
                            $('#noDataMessage').hide();
                        } else {
                            $('#hikersTable tbody').empty();
                            $('#pagination').empty();
                            $('#tableInfo').text('Showing 0 to 0 of 0 entries');
                            $('#noDataMessage').show();
                        }
                    },
                    error: function(xhr, status, error) {
                        hideLoading();
                        console.error('Error loading hikers:', error);
                        alert('Error loading data. Please try again.');
                    }
                });
            }

            function renderTable(data) {
                let html = '';
                data.forEach(function(hiker) {
                    let statusBadge = getStatusBadge(hiker.status);
                    html += `
                <tr>
                    <td>
                        <i class="icon-base ri ri-user-3-line icon-22px text-info me-3"></i>
                        <span>${hiker.user_name}</span>
                    </td>
                    <td>${hiker.email}</td>
                    <td>
                        <i class="icon-base ri ri-mountain-line icon-22px text-success me-2"></i>
                        ${hiker.mountain_name}
                    </td>
                    <td>${hiker.checkin_time}</td>
                    <td>${hiker.checkout_time}</td>
                    <td>${statusBadge}</td>
                    <td>
                        <div class="dropdown">
                            <button type="button" class="btn p-0 dropdown-toggle hide-arrow shadow-none" data-bs-toggle="dropdown">
                                <i class="icon-base ri ri-more-2-line icon-18px"></i>
                            </button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="javascript:void(0);" onclick="viewHiker(${hiker.booking_id})">
                                    <i class="icon-base ri ri-eye-line icon-18px me-2"></i>
                                    View
                                </a>
                                <a class="dropdown-item" href="javascript:void(0);" onclick="editHiker(${hiker.booking_id})">
                                    <i class="icon-base ri ri-pencil-line icon-18px me-2"></i>
                                    Edit
                                </a>
                                <a class="dropdown-item text-danger" href="javascript:void(0);" onclick="deleteHiker(${hiker.booking_id})">
                                    <i class="icon-base ri ri-delete-bin-6-line icon-18px me-2"></i>
                                    Delete
                                </a>
                            </div>
                        </div>
                    </td>
                </tr>
            `;
                });
                $('#hikersTable tbody').html(html);
            }

            function getStatusBadge(status) {
                let badgeClass = '';
                switch (status.toLowerCase()) {
                    case 'active':
                    case 'checked-in':
                        badgeClass = 'bg-label-success';
                        break;
                    case 'pending':
                        badgeClass = 'bg-label-warning';
                        break;
                    case 'completed':
                    case 'checked-out':
                        badgeClass = 'bg-label-primary';
                        break;
                    case 'cancelled':
                        badgeClass = 'bg-label-danger';
                        break;
                    default:
                        badgeClass = 'bg-label-secondary';
                }
                return `<span class="badge rounded-pill ${badgeClass} me-1">${status}</span>`;
            }

            function renderPagination() {
                const totalPages = Math.ceil(totalRecords / itemsPerPage);
                let html = '';
                if (totalPages <= 1) {
                    $('#pagination').empty();
                    return;
                }
                html += `
            <li class="page-item ${currentPage === 1 ? 'disabled' : ''}">
                <a class="page-link" href="javascript:void(0);" onclick="changePage(${currentPage - 1})">
                    <i class="ri-arrow-left-s-line"></i>
                </a>
            </li>
        `;
                const startPage = Math.max(1, currentPage - 2);
                const endPage = Math.min(totalPages, startPage + 4);
                if (startPage > 1) {
                    html +=
                        `<li class="page-item"><a class="page-link" href="javascript:void(0);" onclick="changePage(1)">1</a></li>`;
                    if (startPage > 2) {
                        html += `<li class="page-item disabled"><span class="page-link">...</span></li>`;
                    }
                }
                for (let i = startPage; i <= endPage; i++) {
                    html += `
                <li class="page-item ${i === currentPage ? 'active' : ''}">
                    <a class="page-link" href="javascript:void(0);" onclick="changePage(${i})">${i}</a>
                </li>
            `;
                }
                if (endPage < totalPages) {
                    if (endPage < totalPages - 1) {
                        html += `<li class="page-item disabled"><span class="page-link">...</span></li>`;
                    }
                    html +=
                        `<li class="page-item"><a class="page-link" href="javascript:void(0);" onclick="changePage(${totalPages})">${totalPages}</a></li>`;
                }
                html += `
            <li class="page-item ${currentPage === totalPages ? 'disabled' : ''}">
                <a class="page-link" href="javascript:void(0);" onclick="changePage(${currentPage + 1})">
                    <i class="ri-arrow-right-s-line"></i>
                </a>
            </li>
        `;
                $('#pagination').html(html);
            }

            window.changePage = function(page) {
                if (page < 1 || page > Math.ceil(totalRecords / itemsPerPage)) return;
                currentPage = page;
                loadHikers();
            };

            function updateTableInfo() {
                const start = (currentPage - 1) * itemsPerPage + 1;
                const end = Math.min(currentPage * itemsPerPage, totalRecords);
                $('#tableInfo').text(`Showing ${start} to ${end} of ${totalRecords} entries`);
            }

            function showLoading() {
                $('#loadingSpinner').show();
                $('#hikersTable tbody').empty();
                $('#noDataMessage').hide();
            }

            function hideLoading() {
                $('#loadingSpinner').hide();
            }

            window.viewHiker = function(bookingId) {
                console.log('View hiker:', bookingId);
            };

            window.editHiker = function(bookingId) {
                console.log('Edit hiker:', bookingId);
            };

            window.deleteHiker = function(bookingId) {
                if (confirm('Are you sure you want to delete this booking?')) {
                    console.log('Delete hiker:', bookingId);
                    $.ajax({
                        url: `/hikers/${bookingId}`,
                        type: 'DELETE',
                        data: {
                            _token: '{{ csrf_token() }}'
                        },
                        success: function(response) {
                            alert('Booking deleted successfully');
                            loadHikers();
                        },
                        error: function(xhr, status, error) {
                            alert('Error deleting booking. Please try again.');
                        }
                    });
                }
            };
        });
    </script>
@endpush
