@extends('dashboard.layouts.app')
@section('content')
    <div class="content-wrapper">
        <div class="container-xxl flex-grow-1 container-p-y">
            <div class="row gy-6">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="mb-0">Riwayat Pendakian Pendaki</h5>
                        <div class="card-header-elements">
                            <input type="text" id="searchInput" class="form-control" placeholder="Cari pendaki..."
                                style="width: 250px;">
                        </div>
                    </div>
                    <div class="table-responsive text-nowrap">
                        <table class="table" id="hikerHistoryTable">
                            <thead>
                                <tr>
                                    <th>Nama Pendaki</th>
                                    <th>Gunung</th>
                                    <th>Tanggal Pendakian</th>
                                    <th>Check-in</th>
                                    <th>Check-out</th>
                                    <th>Total Durasi</th>
                                    <th>Tracking Rute</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody class="table-border-bottom-0">
                                <!-- Data will be loaded via AJAX -->
                            </tbody>
                        </table>
                    </div>

                    <!-- Loading spinner -->
                    <div id="loadingSpinner" class="text-center p-4" style="display: none;">
                        <div class="spinner-border text-primary" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                    </div>

                    <!-- No data message -->
                    <div id="noDataMessage" class="text-center p-4" style="display: none;">
                        <p class="text-muted">Tidak ada riwayat pendakian ditemukan.</p>
                    </div>

                    <!-- Pagination -->
                    <div class="card-footer">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <span id="tableInfo" class="text-muted">Menampilkan 0 sampai 0 dari 0 entri</span>
                            </div>
                            <div class="col-md-6">
                                <nav aria-label="Table pagination">
                                    <ul class="pagination justify-content-end mb-0" id="pagination">
                                        <!-- Pagination will be generated by JavaScript -->
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Detail Modal -->
        <div class="modal fade" id="detailModal" tabindex="-1" aria-labelledby="detailModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-xl">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="detailModalLabel">Detail Riwayat Pendakian</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div id="detailContent">
                            <!-- Detail content will be loaded here -->
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- Tracking Route Modal -->
        <div class="modal fade" id="trackingModal" tabindex="-1" aria-labelledby="trackingModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-xl">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="trackingModalLabel">Rute Tracking Pendakian</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div id="mapContainer" style="height: 500px; width: 100%;">
                            <!-- Map will be loaded here -->
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                    </div>
                </div>
            </div>
        </div>

        <footer class="content-footer footer bg-footer-theme">
            <div class="container-xxl">
                <div
                    class="footer-container d-flex align-items-center justify-content-between py-4 flex-md-row flex-column">
                    <div class="mb-2 mb-md-0">
                        &#169;
                        <script>
                            document.write(new Date().getFullYear());
                        </script>, Mountain Management System
                    </div>
                </div>
            </div>
        </footer>

        <div class="content-backdrop fade"></div>
    </div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function() {
            let currentPage = 1;
            let itemsPerPage = 10;
            let searchTerm = '';
            let totalRecords = 0;
            loadHikerHistory();

            let searchTimeout;
            $('#searchInput').on('keyup', function() {
                clearTimeout(searchTimeout);
                searchTerm = $(this).val();
                searchTimeout = setTimeout(function() {
                    currentPage = 1;
                    loadHikerHistory();
                }, 500);
            });

            function loadHikerHistory() {
                showLoading();
                $.ajax({
                    url: '{{ route('hiker-history.data') }}',
                    type: 'GET',
                    data: {
                        search: searchTerm,
                        start: (currentPage - 1) * itemsPerPage,
                        length: itemsPerPage,
                        order_column: 'mb.hike_date',
                        order_dir: 'desc'
                    },
                    success: function(response) {
                        hideLoading();
                        totalRecords = response.recordsTotal;
                        if (response.data && response.data.length > 0) {
                            renderTable(response.data);
                            renderPagination();
                            updateTableInfo();
                            $('#noDataMessage').hide();
                        } else {
                            $('#hikerHistoryTable tbody').empty();
                            $('#pagination').empty();
                            $('#tableInfo').text('Menampilkan 0 sampai 0 dari 0 entri');
                            $('#noDataMessage').show();
                        }
                    },
                    error: function(xhr, status, error) {
                        hideLoading();
                        console.error('Error loading hiker history:', error);
                        alert('Error loading data. Silakan coba lagi.');
                    }
                });
            }

            function renderTable(data) {
                let html = '';
                data.forEach(function(history) {
                    let statusBadge = getStatusBadge(history.status);
                    let trackingBadge = getTrackingBadge(history.has_tracking, history.tracking_info);

                    html += `
                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                            <i class="icon-base ri ri-user-3-line icon-22px text-info me-3"></i>
                            <div>
                                <span class="fw-medium">${history.user_name}</span>
                                <br>
                                <small class="text-muted">${history.email}</small>
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="d-flex align-items-center">
                            <i class="icon-base ri ri-mountain-line icon-22px text-success me-2"></i>
                            <div>
                                <span class="fw-medium">${history.mountain_name}</span>
                                <br>
                                <small class="text-muted">${history.mountain_location}</small>
                            </div>
                        </div>
                    </td>
                    <td>
                        <div>
                            <span class="fw-medium">${history.hike_date}</span>
                            ${history.return_date !== '-' ? '<br><small class="text-muted">s/d ' + history.return_date + '</small>' : ''}
                        </div>
                    </td>
                    <td>
                        <span class="badge bg-label-success">${history.checkin_time}</span>
                    </td>
                    <td>
                        ${history.checkout_time !== '-' ? 
                            '<span class="badge bg-label-primary">' + history.checkout_time + '</span>' : 
                            '<span class="badge bg-label-warning">Belum checkout</span>'
                        }
                    </td>
                    <td>
                        <div class="d-flex align-items-center">
                            <i class="icon-base ri ri-time-line icon-18px text-primary me-2"></i>
                            <span class="fw-medium">${history.total_duration}</span>
                        </div>
                    </td>
                    <td>${trackingBadge}</td>
                    <td>${statusBadge}</td>
                    <td>
                        <div class="dropdown">
                            <button type="button" class="btn p-0 dropdown-toggle hide-arrow shadow-none" data-bs-toggle="dropdown">
                                <i class="icon-base ri ri-more-2-line icon-18px"></i>
                            </button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="javascript:void(0);" onclick="viewDetail(${history.booking_id})">
                                    <i class="icon-base ri ri-eye-line icon-18px me-2"></i>
                                    Lihat Detail
                                </a>
                                ${history.has_tracking ? 
                                    '<a class="dropdown-item" href="javascript:void(0);" onclick="viewTracking(' + history.booking_id + ')">' +
                                    '<i class="icon-base ri ri-map-pin-line icon-18px me-2"></i>' +
                                    'Lihat Rute' +
                                    '</a>' : ''
                                }
                                <a class="dropdown-item" href="javascript:void(0);" onclick="exportData(${history.booking_id})">
                                    <i class="icon-base ri ri-download-line icon-18px me-2"></i>
                                    Export Data
                                </a>
                            </div>
                        </div>
                    </td>
                </tr>
            `;
                });
                $('#hikerHistoryTable tbody').html(html);
            }

            function getStatusBadge(status) {
                let badgeClass = '';
                let statusText = status;
                switch (status.toLowerCase()) {
                    case 'active':
                        badgeClass = 'bg-label-warning';
                        statusText = 'Aktif';
                        break;
                    case 'completed':
                        badgeClass = 'bg-label-success';
                        statusText = 'Selesai';
                        break;
                    case 'cancelled':
                        badgeClass = 'bg-label-danger';
                        statusText = 'Dibatalkan';
                        break;
                    default:
                        badgeClass = 'bg-label-secondary';
                }
                return `<span class="badge rounded-pill ${badgeClass}">${statusText}</span>`;
            }

            function getTrackingBadge(hasTracking, trackingInfo) {
                if (hasTracking) {
                    return `<span class="badge bg-label-success">
                        <i class="icon-base ri ri-map-pin-line icon-12px me-1"></i>
                        ${trackingInfo}
                    </span>`;
                } else {
                    return `<span class="badge bg-label-secondary">
                        <i class="icon-base ri ri-map-pin-off-line icon-12px me-1"></i>
                        Tidak ada tracking
                    </span>`;
                }
            }

            function renderPagination() {
                const totalPages = Math.ceil(totalRecords / itemsPerPage);
                let html = '';
                if (totalPages <= 1) {
                    $('#pagination').empty();
                    return;
                }

                html += `
            <li class="page-item ${currentPage === 1 ? 'disabled' : ''}">
                <a class="page-link" href="javascript:void(0);" onclick="changePage(${currentPage - 1})">
                    <i class="ri-arrow-left-s-line"></i>
                </a>
            </li>
        `;

                const startPage = Math.max(1, currentPage - 2);
                const endPage = Math.min(totalPages, startPage + 4);

                if (startPage > 1) {
                    html +=
                        `<li class="page-item"><a class="page-link" href="javascript:void(0);" onclick="changePage(1)">1</a></li>`;
                    if (startPage > 2) {
                        html += `<li class="page-item disabled"><span class="page-link">...</span></li>`;
                    }
                }

                for (let i = startPage; i <= endPage; i++) {
                    html += `
                <li class="page-item ${i === currentPage ? 'active' : ''}">
                    <a class="page-link" href="javascript:void(0);" onclick="changePage(${i})">${i}</a>
                </li>
            `;
                }

                if (endPage < totalPages) {
                    if (endPage < totalPages - 1) {
                        html += `<li class="page-item disabled"><span class="page-link">...</span></li>`;
                    }
                    html +=
                        `<li class="page-item"><a class="page-link" href="javascript:void(0);" onclick="changePage(${totalPages})">${totalPages}</a></li>`;
                }

                html += `
            <li class="page-item ${currentPage === totalPages ? 'disabled' : ''}">
                <a class="page-link" href="javascript:void(0);" onclick="changePage(${currentPage + 1})">
                    <i class="ri-arrow-right-s-line"></i>
                </a>
            </li>
        `;
                $('#pagination').html(html);
            }

            window.changePage = function(page) {
                if (page < 1 || page > Math.ceil(totalRecords / itemsPerPage)) return;
                currentPage = page;
                loadHikerHistory();
            };

            function updateTableInfo() {
                const start = (currentPage - 1) * itemsPerPage + 1;
                const end = Math.min(currentPage * itemsPerPage, totalRecords);
                $('#tableInfo').text(`Menampilkan ${start} sampai ${end} dari ${totalRecords} entri`);
            }

            function showLoading() {
                $('#loadingSpinner').show();
                $('#hikerHistoryTable tbody').empty();
                $('#noDataMessage').hide();
            }

            function hideLoading() {
                $('#loadingSpinner').hide();
            }

            window.viewDetail = function(bookingId) {
                $.ajax({
                    url: '{{ route('hiker-history.detail', ':bookingId') }}'.replace(':bookingId',
                        bookingId),
                    type: 'GET',
                    success: function(response) {
                        renderDetailModal(response);
                        $('#detailModal').modal('show');
                    },
                    error: function(xhr, status, error) {
                        alert('Error loading detail. Silakan coba lagi.');
                    }
                });
            };

            window.viewTracking = function(bookingId) {
                $.ajax({
                    url: '{{ route('hiker-history.tracking-route', ':bookingId') }}'.replace(
                        ':bookingId', bookingId),
                    type: 'GET',
                    success: function(response) {
                        if (response.route && response.route.length > 0) {
                            renderTrackingMap(response.route);
                            $('#trackingModal').modal('show');
                        } else {
                            alert('Tidak ada data tracking untuk pendakian ini.');
                        }
                    },
                    error: function(xhr, status, error) {
                        alert('Error loading tracking data. Silakan coba lagi.');
                    }
                });
            };

            window.exportData = function(bookingId) {
                window.open(`/dashboard/hiker-history/${bookingId}/export`, '_blank');
            };

            function renderDetailModal(data) {
                let membersHtml = '';
                if (data.members && data.members.length > 0) {
                    data.members.forEach(function(member, index) {
                        membersHtml += `
                    <tr>
                        <td>${index + 1}</td>
                        <td>${member.name || '-'}</td>
                        <td>${member.nik || '-'}</td>
                        <td>${member.phone || '-'}</td>
                        <td>${member.emergency_contact || '-'}</td>
                    </tr>
                `;
                    });
                }

                let equipmentHtml = '';
                if (data.equipment_rentals && data.equipment_rentals.length > 0) {
                    data.equipment_rentals.forEach(function(equipment) {
                        equipmentHtml += `
                    <tr>
                        <td>${equipment.name}</td>
                        <td>${equipment.quantity}</td>
                        <td><span class="badge ${equipment.status === 'returned' ? 'bg-success' : 'bg-warning'}">${equipment.status === 'returned' ? 'Dikembalikan' : 'Dipinjam'}</span></td>
                    </tr>
                `;
                    });
                }

                let durationHtml = '-';
                if (data.total_duration) {
                    const duration = data.total_duration;
                    durationHtml =
                        `${duration.days > 0 ? duration.days + ' hari ' : ''}${duration.hours} jam ${duration.minutes} menit`;
                }

                const detailHtml = `
            <div class="row">
                <div class="col-md-6">
                    <h6>Informasi Pendaki</h6>
                    <table class="table table-borderless">
                        <tr><td class="fw-medium">Nama:</td><td>${data.booking.user_name}</td></tr>
                        <tr><td class="fw-medium">Email:</td><td>${data.booking.email}</td></tr>
                        <tr><td class="fw-medium">Telepon:</td><td>${data.booking.phone}</td></tr>
                        <tr><td class="fw-medium">Kontak Darurat:</td><td>${data.booking.emergency_contact || '-'}</td></tr>
                    </table>
                </div>
                <div class="col-md-6">
                    <h6>Informasi Pendakian</h6>
                    <table class="table table-borderless">
                        <tr><td class="fw-medium">Gunung:</td><td>${data.booking.mountain_name}</td></tr>
                        <tr><td class="fw-medium">Lokasi:</td><td>${data.booking.mountain_location}</td></tr>
                        <tr><td class="fw-medium">Tanggal Pendakian:</td><td>${data.booking.hike_date}</td></tr>
                        <tr><td class="fw-medium">Tanggal Kembali:</td><td>${data.booking.return_date || '-'}</td></tr>
                        <tr><td class="fw-medium">Jumlah Tim:</td><td>${data.booking.team_size} orang</td></tr>
                    </table>
                </div>
            </div>

            <div class="row mt-4">
                <div class="col-12">
                    <h6>Waktu & Durasi</h6>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="card bg-label-success">
                                <div class="card-body text-center">
                                    <i class="icon-base ri ri-login-box-line icon-32px mb-2"></i>
                                    <h6 class="mb-1">Check-in</h6>
                                    <small>${data.booking.checkin_time || '-'}</small>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="card bg-label-primary">
                                <div class="card-body text-center">
                                    <i class="icon-base ri ri-logout-box-line icon-32px mb-2"></i>
                                    <h6 class="mb-1">Check-out</h6>
                                    <small>${data.booking.checkout_time || 'Belum checkout'}</small>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="card bg-label-info">
                                <div class="card-body text-center">
                                    <i class="icon-base ri ri-time-line icon-32px mb-2"></i>
                                    <h6 class="mb-1">Total Durasi</h6>
                                    <small>${durationHtml}</small>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="card bg-label-warning">
                                <div class="card-body text-center">
                                    <i class="icon-base ri ri-map-pin-line icon-32px mb-2"></i>
                                    <h6 class="mb-1">Tracking Points</h6>
                                    <small>${data.location_logs.length} titik</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            ${membersHtml ? `
                    <div class="mt-4">
                        <h6>Anggota Tim</h6>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama</th>
                                        <th>NIK</th>
                                        <th>Telepon</th>
                                        <th>Kontak Darurat</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    ${membersHtml}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    ` : ''}

            ${equipmentHtml ? `
                    <div class="mt-4">
                        <h6>Penyewaan Peralatan</h6>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>Nama Peralatan</th>
                                        <th>Jumlah</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    ${equipmentHtml}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    ` : ''}
        `;

                $('#detailContent').html(detailHtml);
            }

            function renderTrackingMap(routeData) {
                $('#mapContainer').html(`
            <div class="text-center">
                <i class="icon-base ri ri-map-pin-line icon-48px text-primary mb-3"></i>
                <h6>Peta Rute Tracking</h6>
                <p class="text-muted mb-4">Total ${routeData.length} titik tracking</p>
                <div class="alert alert-info">
                    <strong>Info:</strong> Fitur peta akan diimplementasikan dengan Google Maps atau Leaflet.
                    <br>Rute dimulai dari: ${routeData[0].timestamp}
                    <br>Rute berakhir di: ${routeData[routeData.length - 1].timestamp}
                </div>
            </div>
        `);
            }
        });
    </script>
@endpush
